CREATE TABLE STUDENTS (
    ID INT PRIMARY KEY,
	NAME TEXT NOT NULL,
	AGE INT,
	CITY TEXT,
	GRADE REAL NOT NULL
);
INSERT INTO STUDENTS (ID,NAME,AGE,CITY,GRADE) VALUES
(1,'Noa',15,'Tel Aviv',92.5),
(2,'Liam',16,'Haifa',88.0),
(3,'Maya',15,'Netanya',95.0),
(4,'Omer',17,'Jerusalem',81.5);
